### ISSUE TITLE
error             indent            Expected indentation of 0 space characters but found 4

### ISSUE THREAD

**Issue by jiangyoucai** [LeslieYQ/vue-format#4]
I use this plugins to format my *.vue in atom,but the webpack give me some errors like 'error             indent            Expected indentation of 0 space characters but found 4',what can i do to resolve them ？thank you

**Comment by LeslieYQ** [comment]
@jiangyoucai 
 'error indent Expected indentation of 0 space characters but found 4' .
I think it's something wrong with other webpack plugins， such as stylus-loader， sass-loader。

Because they have a strict format requirements。

Can you give me more details？

**Comment by jiangyoucai** [comment]
i am use the default confi of the vue+webpack,https://github.com/vuejs/vue-cli
then format the *.vue,and then get the error

**Comment by LeslieYQ** [comment]
```
<template>
  <div id="app">
    <img class="logo" src="./assets/logo.png">
    <hello></hello>
  </div>
</template>

<script>
import Hello from './components/Hello'

export default {
  components: {
    Hello
  }
}
</script>

<style>
body {
  font-family: Helvetica, sans-serif;
}
</style>
```

like this？？

**Comment by jiangyoucai** [comment]
yes,if i format the file,the webpack will give me some errors,because the plugin set 4 spaces but the eslint need 2spaces

**Comment by LeslieYQ** [comment]
you can editor the eslint config,  .eslintrc.js

`
'generator-star-spacing': [2, { 'before': true, 'after': true }],
    'guard-for-in': 0,
    'handle-callback-err': [2, '^(err|error)$' ],
    'indent': [2, 2, { 'SwitchCase': 1 }],
    'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
`
or you can drop the eslint.

next step I will add config file.

chinese people?

**Comment by jiangyoucai** [comment]
thank you, i am in shenzhen

**Comment by LeslieYQ** [comment]
我在北京。。。 @jiangyoucai

**Comment by jiangyoucai** [comment]
这是正确的配置文件，我已经测试通过了
// add your custom rules here
    'rules': {
        // allow paren-less arrow functions
        'arrow-parens': 0,
        // allow debugger during development
        'no-debugger': process.env.NODE_ENV === 'production' ? 4 : 0,
        'generator-star-spacing': [2, {
            'before': false,
            'after': true
        }],
        'guard-for-in': 0,
        'handle-callback-err': [2, '^(err|error)$'],
        'indent': [2, 4, {
            'SwitchCase': 1
        }],
        'key-spacing': [2, {
            'beforeColon': false,
            'afterColon': true
        }],
        'space-before-function-paren': [0, 'always'], //函数定义时括号前面要不要有空格
        'no-multiple-empty-lines': [2, {
            'max': 2
        }], //空行最多不能超过2行
        'eol-last': 0, //文件以单一的换行符结束
    }

**Comment by jiangyoucai** [comment]
另外还有问题
错误：自动格式化的结果
export default {
++++data() {
++++++++++++return vmAccount
++++++++},
++++++++ready() {
++++++++++++var account = store.get('account')
++++++++++++if (account !== undefined) {
++++++++++++++++this.accountLogin(account)
++++++++++++} else {
++++++++++++++++router.go({
++++++++++++++++++++path: '/login'
++++++++++++++++})
++++++++++++}
++++++++}
}
从return向下，都多了4个空格
正确：手动调整结果
export default {
++++data() {
++++++++return vmAccount
++++},
++++ready() {
++++++++var account = store.get('account')
++++++++if (account !== undefined) {
++++++++++++this.accountLogin(account)
++++++++} else {
++++++++++++router.go({
++++++++++++++++path: '/login'
++++++++++++})
++++++++}
++++}
}

**Comment by LeslieYQ** [comment]
现在对es6的支持很不好，还有一些模板， 例如 css的 stylus  less sass等等，

html  jade等等，这些需要我忙过这段时间了 慢慢优化了。

**Comment by ganksolo** [comment]
mark this place~

**Comment by LeslieYQ** [comment]
OK I will do it as soon as possible
