### ISSUE TITLE
The indent_size is “4”, even the .jsbeautifyrc is set to “2”T_T

### ISSUE THREAD

**Issue by qiansen1386** [LeslieYQ/vue-format#6]
Before(Also expected)
![image](https://cloud.githubusercontent.com/assets/1759658/14424177/4552fdac-0012-11e6-87dc-fdf7e68c9c20.png)
After
![image](https://cloud.githubusercontent.com/assets/1759658/14424193/54debba8-0012-11e6-87ea-58df0c372ffd.png)

大哥，这可咋整啊。

**Comment by LeslieYQ** [comment]
没有太明白？？  是多了换行么？

**Comment by qiansen1386** [comment]
多了换行是一点，不知道是不是插件冲突。
主要是缩进啊，配置了两个空格的缩进，可是格式化出来是4个空格……

**Comment by qiansen1386** [comment]
抱歉，图配错了……
![image](https://cloud.githubusercontent.com/assets/1759658/14449331/630a1f82-00a4-11e6-9a82-5007e7dac048.png)

这个效果是换用 standard-formatter 出来的。感觉 Standard-formatter 也可以用吧。

**Comment by LeslieYQ** [comment]
最开始Standard-formatter貌似不能用，后面不知道是不是支持了，其实是因为我现在没有时间维护，不支持配置的，直接使用的原生的4个。 后面本来想加来着，一直没来得及。

**Comment by qiansen1386** [comment]
这样啊……确实维护开源组件挺累的。
好像，最近的 `language-vue` 插件搭配 `standard-formatter` 目前还没有什么问题的。感觉这个 `formatter` 其实可以下架了。

**Comment by jenil** [comment]
how to fix this?

**Comment by qiansen1386** [comment]
@jgog You can use `Standard-formatter` + `language-vue` combination as alternative

**Comment by jenil** [comment]
I tried Standard Formatter but it the output is incorrect

Gives:

```
import Toolbar from 'components/Toolbar'

export default {
  components: {
  Toolbar}
}
```

Expected:

```
import Toolbar from 'components/Toolbar'

export default {
  components: {
    Toolbar
  }
}
```

**Comment by qiansen1386** [comment]
@jgog I got no clue, my friend. Since we are certainly not experts for it. I think you should report it to Standard formatter community to get further assistance. :smiley:

**Comment by jenil** [comment]
Ya thanks!
